# _config.yml
title: srikar's portfolio
description: A description of your portfolio or the purpose of your site
theme: jekyll-theme-cayman
# General Site Information


# SEO Meta Tags for Search Engine Optimization
seo:
  # Site-wide meta description for search engines
  description: "Full Stack Developer & Problem Solver. Check out my projects, skills, and experience!"
  
  # Keywords related to the portfolio to help search engines understand the content
  keywords: "Full Stack Developer, Web Development, Software Engineer, C++, Python, JavaScript, React, Node.js, Portfolio"

  # Open Graph Meta Tags for social media preview
  og:
    title: "Srikar Kulkarni's Portfolio"
    description: "Explore my technical journey as a Full Stack Developer."
    image: "/assets/images/og-image.jpg"  # Image shown on social media when shared
    url: "https://yourportfolio.com"  # Full URL of your portfolio
    type: "website"

  # Twitter Card Meta Tags
  twitter:
    card: "summary_large_image"
    title: "Srikar Kulkarni's Portfolio"
    description: "Browse my projects and learn more about my skills and experience."
    image: "/assets/images/twitter-card.jpg"  # Twitter card image
    creator: "@yourtwitterhandle"  # Your Twitter handle

# Performance Enhancements
performance:
  # Enable caching headers for faster load times
  cache_control: "max-age=3600, must-revalidate"
  
  # Enable compression for JavaScript and CSS files
  compress_assets: true
  
  # Enable lazy loading of images for improved performance
  lazy_load_images: true
